### PR TITLE
Remove all builtins

### PR DESCRIPTION
**Pull request by ocharles**
This commit removes all the builtins around version ranges in favour of just
using Text.

Advantages:

* Can work with the rest of the Dhall ecosystem - `dhall`, `dhall-hash` and
  `dhalli` now all work out-of-the-box with dhall-to-cabal.

Disadvantages:

* If you enter an invalid version number, we can't associate that with a source
  location so error messages become worse. This was already the case with the
  "v" helper function.

* The type annotation doesn't tell you as much as before. E.g., a dependency is
  now { package : Text, bounds : Text }, which you can just about figure out (if
  you know Cabal). The Licenses are much less clear, with things like < AGPL :
  Optional Text> giving no indication that the text is actually the AGPL version
  number.

### CODE REVIEW

**Comment by ocharles** [comment]
Basically the status quo makes me sad because it doesn't work with `dhall` and `dhall-hash`, and this change makes me sad because the types are much less explanatory.

There is one option that we haven't considered, which is supplying all those builtins as function arguments to the top-level `dhall-to-cabal` expression. That is, you would write:

```haskell
\(VersionRange : Type) -> \(majorVersion : List Natural -> VersionRange) -> ...
```

as the header to your files.

**Comment by Gabriel439** [comment]
@ocharles: Yeah, I actually thought a bit about providing the builtins via a record.  I think it's actually doable once records support type-valued fields.  You could do this:

```
λ(builtins : ./BuiltinsType.dhall) →...
```

... and then that should work.  That way you still get interop with the tooling without losing type safety

**Comment by ocharles** [comment]
Let me do another branch exploring that. I really do like what I get from the context, but I definitely feel the pain of not being able to use `dhall` and friends.

**Comment by Gabriel439** [comment]
@ocharles: I have a branch on my personal laptop with the support for type-valued fields.  I can push it tonight when I get home so you can use it for testing this

**Comment by ocharles** [comment]
> λ(builtins : ./BuiltinsType.dhall) →...

Can you really do this though? It seems to suggest that Dhall supports dependent records. Given https://github.com/dhall-lang/dhall-to-cabal/blob/master/lib/Distribution/Package/Dhall.hs#L599, can you encode that a single `builtins`?

**Comment by Gabriel439** [comment]
Oh yeah, this would require that `VersionRange` is not an opaque type.  If that were the case then you could do this without dependent records.

**Comment by Gabriel439** [comment]
If it had to be an opaque type, then you would need to do something like:

```haskell
λ(VersionRange : Type) → λ(builtins : ./Builtins VersionRange) → ...
```

**Comment by ocharles** [comment]
Rejected in favour of #28

**Pull request closed without merging**
