### PR TITLE
Adapt golden tests to last version of lib

### PR DESCRIPTION
**Pull request by jneira**

### CODE REVIEW

**Comment by ocharles** [comment]
Thanks. If I'm understanding correctly, this change only improves the (currently poor) state of testing by now allowing a test case to pass - is that correct?

**Comment by jneira** [comment]
Well, almost that is the situation:
* A little change to adapt GoldenTest to the new version of the lib (to make possible run them):  662ee01 
* Change `dhall-to-cabal.cabal` and `dhall-to-cabal.dhall` to make it pass the test:  aa672b3 and a250e4a (sorry for the misleading commit messages, the changes are not only remove spaces)
* Change `empty-package` to make it pass the test (that was easy :wink: ): 00ef72c 

So only two cases pass them for now. The empty one is almost trivial but dhall-to-cabal involved more changes.

I am not sure if the change (eb68916) to print the diff when the test does not pass is useful in all cases: it can be too much verbose. Let me know and i will revert it.

**Comment by jneira** [comment]
So to complete the "adaption", the rest of dhall files would have to be revised and changed. My idea was to complete them but i wanted some feedback from you about how to continue before do it. Let me know if you think is better to add those changes to this pr or in a new one.

**Comment by quasicomputational** [comment]
Would it be possible to merge the fixes to GoldenTest.hs soon, and then hack on fixing the broken tests incrementally? I'd like to write a few tests in service of #19, but it's currently totally busted.

**Comment by jneira** [comment]
hi, i think the diff output is correct with 226b61f : now it shows the difference between lines instead char by char

**Comment by ocharles** [comment]
This looks like progress, so I'm gonna bring this in as-is. Any further improvements we can do in a separate PR. Thanks for the help, @jneira

**Pull request merged**
