### PR TITLE
[README] Fix typo.

### PR DESCRIPTION
**Pull request by dan-zheng**
`getting stuck in` -> `getting stuck in it`

### CODE REVIEW

**Comment by ocharles** [comment]
I don't see anything wrong with the original text

**Comment by dan-zheng** [comment]
I see, feel free to close.
To me, the sentence sounds a bit more natural with an object for the preposition `getting stuck in`.

**Comment by ocharles** [comment]
I think it might just be a bit of a colloquialism - the whole readme is a tad historic and could do with a rewrite. I'll try and think about this when I get round to that!

**Comment by quasicomputational** [comment]
The original's fine and the proposed change changed the meaning to something slightly different, yeah.

**Pull request closed without merging**
