### PR TITLE
Update prettyprinter

### PR DESCRIPTION
**Pull request by ocharles**

### CODE REVIEW

**Comment by quasicomputational** [comment]
Tests pass with `prettyprinter` 1.3, so let's do it.

**Comment by ocharles** [comment]
How? Even `dhall` doesn't support 1.3 yet - did you just ignore that constraint?

**Comment by quasicomputational** [comment]
Oh, yeah. `cabal new-test all --constraint='prettyprinter >= 1.3' --allow-newer=prettyprinter`. I didn't realise `dhall` didn't support it yet or else I wouldn't've merged!

**Comment by ocharles** [comment]
No worries! If `--allow-newer` worked I think we're all good :+1:

**Pull request merged**
