### PR TITLE
Refactor Dhall.Extra to use utils for build records of dhall >= 1.13

### PR DESCRIPTION
**Pull request by jneira**
I've chosen the easy path of keeping the existing type and functions and making it alias for the dhall ones. Let me know if you think that the best option would be remove them and replace for the new ones.

### CODE REVIEW

**Comment by quasicomputational** [comment]
Negative diffstats make me happy. Good spot that these are redundant now.

**Comment by ocharles** [comment]
Thanks, this looks good. I'm in favour of ripping the aliases out entirely, if you don't mind adding that.

**Comment by jneira** [comment]
@ocharles sure, done!

**Comment by ocharles** [comment]
Nice, thanks!

**Comment by jneira** [comment]
@ocharles beginner git user question: i've seen merges from master in the pr but later i've done a rebase and a forced push... not sure if i should have done it

**Comment by ocharles** [comment]
Ah, a force push will probably remove the `master` merges that i've done. But that's no problem, I can always do it again :) They were fairly automatic merges as there were no conflicts.

**Comment by Gabriel439** [comment]
I believe this is because there was a rebase.  If the derivation is the same before and after the rebase (i.e. the contents of the branch haven't changed) then it confuses Hydra because it doesn't trigger a new build, even though there is a new revision

**Comment by ocharles** [comment]
I know there won't be a new build, but I'm surprised there isn't even an evaluation for the latest commit.

**Comment by Gabriel439** [comment]
Hydra has a "feature" where if the source directory hasn't changed it doesn't trigger a new evaluation

**Comment by jneira** [comment]
oh, sorry for the inconveniences, in other projects rebase seems to be the usual way to integrate master changes

**Comment by Gabriel439** [comment]
@jneira: GitHub supports a "Squash merge" feature which allows you to merge using a single commit without rebasing your pull request.  Under the hood this is powered by `git merge --squash`, which is the equivalent rebase-free command-line workflow

**Pull request merged**
