### PR TITLE
Changes to allow stack build the project

### PR DESCRIPTION
**Pull request by jneira**
After changes to bump cabal spec version of dhall-to-cabal to 2.2 the project cant be built with stack. I've found 2 issues:
* Last lts can't build cabal files with spec > 2.0 -> i've changed the resolver to nightly
* Even with nightly, stack cant build cabal files without build-type (it thinks that is `custom` by default like cabal spec < 2.2 and throws an error: `No Setup.hs or Setup.lhs file found in D:\ws\eta\dhall\dhall-to-etlas\`).
At least with my version: 1.6.5

### CODE REVIEW

**Comment by quasicomputational** [comment]
I think the `build-type` thing is resolved if you upgrade your Stack, which only supports Cabal 2.2 from version 1.7.1. Really, Stack 1.6 ought not to be trying to read a 2.2-spec file at all if it doesn't understand it. On the other hand, the error message is poor and I suspect it'll also happen with prior versions of cabal-install, which also aren't so strict about rejecting `cabal-version` when it's too high, so it probably makes sense to work around. Worth having a comment explaining the situation, though, so that no-one tries to remove the 'redundant' `build-type`.

**Comment by ocharles** [comment]
@jneira out of interest, are you on stack < 1.7.1?

**Comment by jneira** [comment]
@ocharles yeah, 1.6.5 in one of my computers, i think i have 1.7.* in the other one

**Comment by jneira** [comment]
@ocharles does it need me to do some action?

**Comment by ocharles** [comment]
@jneira No action, I've just had a busy week. Catching up now.

**Comment by jneira** [comment]
Just lts-12 was released so i am gonna update the stack.yaml to use it

**Pull request merged**
