### PR TITLE
Hydra

### PR DESCRIPTION
**Pull request by ocharles**

### CODE REVIEW

**Comment by Gabriel439** [comment]
It looks like this pulled in changes from another branch, but it is definitely working: https://hydra.dhall-lang.org/jobset/dhall-to-cabal/30

**Comment by ocharles** [comment]
Not entirely sure why it's building the entire world either, I'll check that.

**Comment by Gabriel439** [comment]
@ocharles: That is normal.  It's because you are using a newer version of GHC than the other `dhall` repositories (which are on GHC 8.0 because they use the default Haskell packages for the 17.09 branch) so GHC 8.2 and the Haskell packages had to be retrieved/built for the first time for your project.  Future builds for your project won't have to rebuild those (unless you add new dependencies)

**Comment by ocharles** [comment]
Merged (manually).

**Pull request closed without merging**
