### PR TITLE
Set the default default-language to Haskell2010

### PR DESCRIPTION
**Pull request by quasicomputational**
This is another divergence from Cabal's defaults, but it's quite good
for our usability. We can figure out a plan to deal with Haskell2020
or whatever when it comes.

### CODE REVIEW

**Comment by ocharles** [comment]
I'm not convinced it's a good idea for dhall-to-cabal to make these calls. I think an empty package should match an empty package in Cabal.

**Comment by quasicomputational** [comment]
Hmm. The boilerplate does annoy me. I'm not convinced people are bothered by a difference between what Cabal does on empty input and what package-description-generation tools do (e.g., hpack has very opinionated defaults and it seems to work well). It's not a disaster if you'd rather keep it with an empty default since I can just fork the defaults locally.

**Comment by ocharles** [comment]
> Hmm. The boilerplate does annoy me

Then factor it out into a Dhall file :smile: You should be able to write your own more opinionated set of defaults, but I'm not sure it's `dhall-ot-cabal`s place.

The hpack comparison is a fair point, and of course if the default isn't what someone wants then they will override the default as necessary. I'll have a think about this. But I do think the point of having a truly configurable format for Cabal files means that we don't need to form opinions.

**Comment by quasicomputational** [comment]
I'll open an issue to talk about ergonomics versus Cabal-faithfulness in defaults more generally.

**Pull request closed without merging**
