### PR TITLE
Add cabal-to-dhall

### PR DESCRIPTION
**Pull request by ocharles**

### CODE REVIEW

**Comment by ocharles** [comment]
@Gabriel439 You will need to change `cabal-version: >= x.y.z` to just `cabal-version: x.y.z`. `dhall-to-cabal` doesn't support version ranges there, as the Cabal documentation suggests that is to be phased out.

**Comment by ocharles** [comment]
Also note this PR isn't entirely cooked yet, the generated Dhall is still too verbose to be useful.

**Comment by Gabriel439** [comment]
Yeah, that's fine

I got further this time, but then ran into the `prettyprinter` error:

```
cabal-to-dhall: »SFail« must not appear in a rendered »SimpleDocStream«. This is a bug in the layout algorithm! Please report this as a bug
CallStack (from HasCallStack):
  error, called at src/Data/Text/Prettyprint/Doc/Render/Util/Panic.hs:13:21 in prettyprinter-1.1.1-L8a4D4oJ5BxAvVt2u6hOn6:Data.Text.Prettyprint.Doc.Render.Util.Panic
```

It looks like the Nix expression needs to specify a newer version for the `dhall` dependency

**Comment by ocharles** [comment]
That's odd, the exact set of deps in this branch are working fine for me. Can you point me to the cabal file/command line call that causes this?

**Comment by Gabriel439** [comment]
I ran it on `dhall.cabal` after changing the Cabal version to be exact

**Comment by ocharles** [comment]
Can you try it on `dhall-to-cabal.cabal`'s output? Or if you have `dhall.dhall`, you can run that through `dhall-to-cabal` and then reverse it. I'll see what's going on with `dhall.cabal`, but it may be as simple as you say with some different dep. versions.

**Comment by Gabriel439** [comment]
The same `cabal-to-dhall` program succeeds on `dhall-to-cabal.dhall`

**Comment by Gabriel439** [comment]
Also, I think I know what the root cause is:

https://github.com/dhall-lang/dhall-haskell/commit/cb03de2a704c1dfa92acdf1c121a0698427feb3f

`dhall.cabal` has a multi-line `description` field whereas `dhall-to-cabal.dhall` does not and the version of `dhall` you're using is before the above fix to correctly print multi-line string literals

**Comment by ocharles** [comment]
Cool, thanks for the hint. I'll try bumping that

**Comment by ocharles** [comment]
Yep, you were right. I've pushed a few fixes and it now works with `dhall.cabal` (though you still have to change the `cabal-version` to a single version).

**Comment by Gabriel439** [comment]
Just tested this out and it works great (once I changed to an exact version range).  The only thing I noticed is that it emits a reference to `./dhall/prelude.dhall` which can be fixed to point to the online Prelude

**Comment by ocharles** [comment]
Yea, I plan to have it point to the GitHub tag of whatever version is
currently running, for now. I think I'll get this merged and released soon,
as I might be running out of steam on this now! Might as well kick it over
the fence and see who else wants to play.

**Pull request merged**
