### PR TITLE
cabal-to-dhall: use defaults in output.

### LINKED ISSUE #57: Use defaults in cabal-to-dhall
`cabal-to-dhall` generates pretty big output, see, e.g., [this test](https://github.com/quasicomputational/dhall-to-cabal/blob/da6c72d2916d737fb191f52a52b1e204f82816b2/golden-tests/cabal-to-dhall/gh-36.dhall) from #54, where four conditionals lead to 16 mostly-empty `Library` records. If defaults were used, it would look more like [this](https://gist.github.com/quasicomputational/b4b16130726f82b0fbd1ed6260d44340#file-input-dhall), which is a lot less scary.

### PR DESCRIPTION
**Pull request by quasicomputational**
This implements using defaults to omit boring fields for Package,
Executable, Library, Benchmark, TestSuite and CompilerOptions, leading
to quite prodigious drops in line-count in the tests and consequent
increases in readability.

Closes #57.

### CODE REVIEW

**Comment by ocharles** [comment]
This approach does work, but I wonder if this would be simpler working purely on Dhall `Expr`s. I can imagine simply turning `mempty` into an `Expr`, and the users given `Package`/`Executable` and essentially taking the asymmetric difference of `users - default` and then taking the merge with `default /\ user`, and finally performing a CSE-like procedure that we do in `--print-type`. I'm just worried there is quite a lot of duplication going on with this approach.

**Comment by quasicomputational** [comment]
Duplication between `dhall/defaults/*.dhall` and Haskell, you mean? My thinking here is that, with the default values embedded in Haskell, we can generate `dhall/defaults/` programmatically and leave the code as the single source of truth.

Hitting it with CSE worries me a bit because we don't have fine control over what will happen; I'd rather be explicit about what and where is going to be defaulted.

**Comment by ocharles** [comment]
Can you fix the conflicts in this?

**Comment by quasicomputational** [comment]
Rebased & fixed up!

**Pull request merged**
