### PR TITLE
WIP: Use defaults in cabal-to-dhall

### PR DESCRIPTION
**Pull request by ocharles**
@quasicomputational this is my take. The use of defaults is almost entirely driven by manipulating Expr's.

### CODE REVIEW

**Comment by quasicomputational** [comment]
I've got a couple of concerns about doing it this way.

First, this doesn't work for `CompilerOptions` properly. Try with this input:

```
cabal-version: 2.0
name: blah
version: 1

executable foo
  main-is: Main.hs
  ghc-options: -O2
```

The generated Dhall file isn't well-formed, because it's using `/\` illegitimately (twice, but the inner one is the more troublesome) where all the fields aren't records. Even if it was `//`, it'd be trouble: the rewritten `CompilerOptions` wants to refer to the `prelude`; we need to be able to say that the default `compiler-options` is `prelude.defaults.CompilerOptions`, but that's a hack in this model.

Next, Cabal has some questionable defaults for itself. We process this input without complaint:

```
cabal-version: 2.0
name: blah
version: 1

executable foo
  build-depends: base
```

...but, again, the output is bogus, because `prelude.defaults.Executable` doesn't have a `main-is` for good reason, but Cabal's default `main-is` is the empty string.

More broadly, this approach is linking two things: Cabal's own idea about what the 'default' for a field is, and `dhall-to-cabal`'s idea. It's not at all compelling to me that these two things should match, and, indeed, there might be good reason to break with Cabal where it's offering weird or unsuitable defaults.

Following on from that, I'd think that, since `prelude.defaults.*` aren't the source of truth about what `dhall-to-cabal`'s default values for fields are, it's extra crucial that we have a way to generate those files.

None of this is insoluble, but I think this approach loses its elegance once it's including stuff like blacklists and manual over-rides for specific fields.

**Comment by ocharles** [comment]
Thanks for the feedback, I'll muse on this when I get a chance. Will you be at ZuriHac this weekend?

**Comment by quasicomputational** [comment]
I just edited it because it was wrong-ish so re-reading it probably a good idea anyway. No, I won't be at ZuriHac, I am afraid. If you're going, have a good time!

**Comment by quasicomputational** [comment]
#98 shows up another potential issue: Cabal's defaults might change in ways we have to adapt to, but it's easy to over-look. In that instance, the `cabal-version` field needs to be bumped or else the easy case for users (omit both `build-type` and `cabal-version`) doesn't do the right thing; the `build-type` change was already made in Cabal, however, so it would've already snuck in if we'd been using this PR's scheme and we would have had to notice the issue when we were upgrading to Cabal 2.2. If we tie Cabal's defaults and dhall-to-cabal's defaults, we'll have to be vigilant about changes when we upgrade Cabal library versions.

**Pull request closed without merging**
