### PR TITLE
CabalToDhall: implement unifyCondTree using associativity.

### LINKED ISSUE #36: cabal-to-dhall does not terminate for some inputs involving conditionals
hi, executing `cabal-to-dhall` with this input:
```
name:                wai-servlet
version:             0.1.5.0
cabal-version:       2.0
                                          
Flag wai-servlet-debug
    Description: print debug output. not suitable for production
    Default:     False

library
  if impl(ghc >= 0.0.9.7)
     cpp-options:      -DINTEROP
  if impl(ghc < 0.7.0.2)
     cpp-options:      -DPURE_JAVA_WITH
  if impl(ghc >= 0.0.9)
     c-sources:        java/Utils.java
  if flag(wai-servlet-debug)
     cpp-options:      -DWAI_SERVLET_DEBUG
```
the execution hangs and eats a lot of memory, eventually exiting with:
```
C:\ws\eta\dhall\dhall-to-etlas>type golden-tests\wai-servlet-ghc.cabal | cabal-t
o-dhall > wai-servlet-ghc.gen.dhall
cabal-to-dhall: getMBlocks: VirtualAlloc MEM_COMMIT failed: The paging file is 
too small for this operation to complete..
```
If i remove *any* of the four conditions (including `if flag(wai-servlet-debug)..`) the program is able to convert the file.

### PR DESCRIPTION
**Pull request by quasicomputational**
I think that this is a lot clearer about what it is doing, rather than
the previous algorithm, which was going wrong and causing #36 and then
making my eyes cross as I tried to figure out precisely *how*.

Fixes #36.

I'm not 100% confident that this is correct since it doesn't round trip (see #53) and the test's output is too big to inspect directly, but I'm not sure where a bug could be hiding in the code.

### CODE REVIEW

**Comment by ocharles** [comment]
Wow, terrific - this looks much simpler. I'll try and get to this soon (along with your other PRs!)

**Comment by quasicomputational** [comment]
OK, now that #53 is fixed, I've verified that the test case can round-trip, so I've got some confidence in this PR.

**Comment by ocharles** [comment]
I've had another read, and this both way simpler and seems to make sense. You walk the CondTree and cat all branches at each level into a single branch essentially. Given that all the tests pass, I'm happy with this. Good to merge?

**Comment by quasicomputational** [comment]
I'm happy with it!

**Pull request merged**
