### PR TITLE
Add stack support

### PR DESCRIPTION
**Pull request by jneira**
Hi!, i am personally happy building dhall-to-cabal with Cabal 2.2 but it seems that with stack support the project can be reach more users.

Greetings

### CODE REVIEW

**Comment by ocharles** [comment]
Yep, not against this. Does Stack give us Cabal 2.2, or would we have to extra-dep that?

**Comment by quasicomputational** [comment]
I'll bump the resolver in the Cabal 2.2 PR to a recent nightly, which will give us both Cabal 2.2 and Dhall 1.14.

**Comment by jneira** [comment]
i've done a quick test with 
```
resolver: lts-11.11
extra-deps:
  - Cabal-2.2.0.1
  - dhall-1.14.0
```
and changing the bounds of Cabal in dhall-to-cabal to `^> 2.2`:
The dependencies are resolved correctly (although it does not compile)

**Comment by ocharles** [comment]
Ok, please commit that. We'll wait for https://github.com/dhall-lang/dhall-to-cabal/pull/42 to land before merging this.

**Comment by ocharles** [comment]
@jneira does everything build now?

**Comment by jneira** [comment]
Fortunately, it does, at least with this version of stack:
```
> stack --version
Version 1.6.5, Git revision 24ab0d6ff07f28276e082c3ce74dfdeb1a2ca9e9 (5514 commits) x86_64 hpack-0.20.0
```

**Comment by ocharles** [comment]
Great! Let's bring this in. Thanks :+1:

**Pull request merged**
