### PR TITLE
Move builtins and VersionRange type to be top-level function arguments

### PR DESCRIPTION
**Pull request by ocharles**
This is the alternative approach and tbh... it's not that bad. With the ability to unpack a record, I could see a typical header be:

```haskell
  λ(VersionRange : Type)
→ λ(builtin : ./dhall/types/builtin.dhall  VersionRange)
→     let stdlib =
            ./dhall/stdlib.dhall  VersionRange builtin
→ ...
```

and from that point on you just refer to things from `stdlib`. With record unpacking, if you need the `Library` type, you could just unpack it:

```haskell
  λ(VersionRange : Type)
→ λ(builtin : ./dhall/types/builtin.dhall  VersionRange)
→     let { Library } =
            ./dhall/stdlib.dhall  VersionRange builtin
→ ...
```

### CODE REVIEW

**Comment by ocharles** [comment]
This is probably my preference over essentially giving up and using `Text`

**Comment by Gabriel439** [comment]
Would it be possible to make `VersionRange` not opaque?  If it were not opaque then you wouldn't need to thread it through to each imported file and you would simplify the header that users require

**Comment by ocharles** [comment]
With everything exported from `stdlib` that isn't a huge problem for users, but does probably make it harder to make things outside of `stdlib`.

I can't really see what it would be if it wasn't opaque. The problem is due to it being a recursive type. https://hackage.haskell.org/package/Cabal-2.0.1.1/docs/Distribution-Version.html#t:VersionRange is what we have to work with, and as every constructor is deprecated, I don't think we should be using those constructors in the public interface.

The smart constructors below (https://hackage.haskell.org/package/Cabal-2.0.1.1/docs/Distribution-Version.html#v:anyVersion) do provide a good set of alternatives for a union, but still - I don't know how to easily model it due to the recursive nature.

If you have any suggestions, I'm all ears. If we can use those smart constructors as alternatives, then `builtins` can be reduced to just `v`.

**Comment by Gabriel439** [comment]
You can get it work even if `VersionRange` a recursive type.  You would just have something like:

```
$ cat ./VersionRange
  ∀(VersionRange : Type)
→ ∀(unionVersionRanges : VersionRange → VersionRange → VersionRange)
→ ...
→ ∀(v : Text → VersionRange)
→ VersionRange

$ cat ./unionVersionRanges
  λ(x : ./VersionRange)
→ λ(y : ./VersionRange)

→ λ(VersionRange : Type)
→ ∀(unionVersionRanges : VersionRange → VersionRange → VersionRange)
→ ...
→ λ(v : Text → VersionRange)
→ unionVersionRanges
  (x VersionRange unionVersionRanges ... v)
  (y VersionRange unionVersionRanges ... v)

$ cat ./v
  λ(x : Text)

→ λ(VersionRange : Type)
→ ∀(unionVersionRanges : VersionRange → VersionRange → VersionRange)
→ ...
→ λ(v : Text → VersionRange)
→ v x

$ cat builtins
{ VersionRange = ./VersionRange
, unionVersionRanges  = ./unionVersionRanges
, ...
, v = ./v
}
```

It would be a bit tedious to author the recursive operations on `VersionRanges`, but it would work.  As far as users are concerned, the `VersionRange` type is still "practically" an opaque type, but that's no worse than making it an actual opaque type.

**Comment by ocharles** [comment]
Ok, but what is the benefit? Or more, what does it look like for someone using `dhall-to-cabal`? I'm not entirely seeing what I - as a user of `dhall-to-cabal` - would have to write. What does the top level type become? Currently (in this branch) it is `\(VersionRange : Type) -> \(builtin : ./Builtins VersionRange)`

**Comment by ocharles** [comment]
Ok, I think I see what you're suggesting - I'll have a new commit in a moment adding that.

**Comment by Gabriel439** [comment]
Yeah, you would be able to change the user-facing code to just `λ(builtins : ./Builtins) → ....` and you would not need to thread the `VersionRange` argument through the code any longer

**Comment by Gabriel439** [comment]
Actually, if you implement `VersionRange` and the associated utilities in the language then you don't even need to take it as an argument to the user's code any more.  You could just add it to the standard library

**Comment by ocharles** [comment]
Alright, I've moved `VersionRange` into Dhall and changed how it's extracted - everything still seems to work ok. It's a really nice trick - I wouldn't have figured that out on my own, thanks!

> Actually, if you implement VersionRange and the associated utilities in the language then you don't even need to take it as an argument to the user's code any more. You could just add it to the standard library

I don't quite understand this. Does it still apply if you read the diff here? You'll see that `dhall-to-cabal.dhall` only really takes `v : Text -> List Natural` as an argument.

**Comment by Gabriel439** [comment]
@ocharles: Yes, my comment still applies.  The user's cabal file doesn't need to be a function that takes a `builtin` argument anymore.  You can provide `VersionRange`, `v`, and `unionVersionRanges` via the `stdlib` now.

Let me use a smaller example to illustrate what I mean.  Suppose that you only had one builtin type, `VersionRange`, and two builtin functions, `thisVersion` and the `unionVersionRanges`.  You can "implement" them in Dhall like this:

```
$ cat ./VersionRange 
  ∀(VersionRange : Type)
→ ∀(thisVersion : List Natural → VersionRange)
→ ∀(unionVersionRanges : VersionRange → VersionRange → VersionRange)
→ VersionRange

$ cat ./thisVersion 
    let thisVersion
        : List Natural → ./VersionRange 
        =   λ(x : List Natural)
          → λ(VersionRange : Type)
          → λ(thisVersion : List Natural → VersionRange)
          → λ(unionVersionRanges : VersionRange → VersionRange → VersionRange)
          → thisVersion x

in  thisVersion

$ cat ./unionVersionRanges 
    let unionVersionRanges
        : ./VersionRange  → ./VersionRange  → ./VersionRange 
        =   λ(x : ./VersionRange )
          → λ(y : ./VersionRange )
          → λ(VersionRange : Type)
          → λ(thisVersion : List Natural → VersionRange)
          → λ(unionVersionRanges : VersionRange → VersionRange → VersionRange)
          → unionVersionRanges
            (x VersionRange thisVersion unionVersionRanges)
            (y VersionRange thisVersion unionVersionRanges)

in  unionVersionRanges

$ cat ./example 
./unionVersionRanges 
(./thisVersion  [ +1, +0 ])
(./unionVersionRanges  (./thisVersion  [ +2, +0 ]) (./thisVersion  [ +3, +0 ]))
```

This is all valid Dhall code with an empty context.  If you normalize `./example` using the `dhall` interpreter, you get the following result:

```
$ dhall <<< './example'
∀(VersionRange : Type) → ∀(thisVersion : List Natural → VersionRange) → ∀(unionVersionRanges : VersionRange → VersionRange → VersionRange) → VersionRange

λ(VersionRange : Type) → λ(thisVersion : List Natural → VersionRange) → λ(unionVersionRanges : VersionRange → VersionRange → VersionRange) → unionVersionRanges (thisVersion [ +1, +0 ]) (unionVersionRanges (thisVersion [ +2, +0 ]) (thisVersion [ +3, +0 ]))
```

Note that normalizing `./example` hasn't really done any actual "work".  It's basically just created an inert abstract syntax tree, **but** this abstract syntax tree type-checks without a custom context because it is preceded by the necessary lambda abstractions that provide the necessary context.

Then you can configure the `extract` function for the Haskell `VersionRange` to recognize an expression of the following shape:

```haskell
  λ(VersionRange : Type)
→ λ(thisVersion : List Natural → VersionRange)
→ λ(unionVersionRanges : VersionRange → VersionRange → VersionRange)
→ ...
```

... and just strip away the lambda abstraction prefix, leaving behind an abstract syntax tree that you then interpret using the corresponding Haskell functions.  For example, using the above example you would start with this expression:

```
λ(VersionRange : Type) → λ(thisVersion : List Natural → VersionRange) → λ(unionVersionRanges : VersionRange → VersionRange → VersionRange) → unionVersionRanges (thisVersion [ +1, +0 ]) (unionVersionRanges (thisVersion [ +2, +0 ]) (thisVersion [ +3, +0 ]))
```

... strip away the lambda abstraction prefix, leaving behind:

```
 unionVersionRanges (thisVersion [ +1, +0 ]) (unionVersionRanges (thisVersion [ +2, +0 ]) (thisVersion [ +3, +0 ]))
```

... and then translate that to the matching Haskell functions to produce a Haskell `VersionRange`.  This in turn implies that you no longer need the user's `*.dhall` file to take a built-in record as an argument.  You would just add `./VersionRange`, `./thisVersion`, and `./unionVersionRanges` directly to the `stdlib` record you've already created.

**Comment by ocharles** [comment]
Oh, sorry - I forgot to push some files, because I've already done all of that for `VersionRange`.

My question was actually just about `v : Text -> List Natural` which has nothing to do with `VersionRange` (it just builds versions). With my latest changes, the only thing I supply as a top level function argument is essentially the `v` function:

```haskell
\(v : Text -> List Natural) -> 
...
```

I don't believe I can otherwise represent `v` in just Dhall, because I can't give it a body (it is not total, for one).

We could, however, use the same trick:

```
$ cat ./Version
forall (Version : Type) -> forall (v : Text -> Version) -> Version

$ cat ./v
\(str : Text) -> \(Version : Type) -> \(v : Text -> Version) -> v str
```

This means that `Version` becomes an opaque type (users can only construct a `Version`, they are given no real operations on them). In one sense this is actually nice, as types become more descriptive. On the other hand, a `Version` is exactly a `List Natural` (https://hackage.haskell.org/package/Cabal-2.0.1.1/docs/Distribution-Version.html#v:mkVersion) so perhaps this is needlessly obtuse.

**Comment by ocharles** [comment]
Ok, I went ahead and did the same trick with `Version` too. Users no longer have to write functions at all, just ordinary records. I think the limitation of

> users can only construct a Version, they are given no real operations on them

isn't too bad.

**Comment by Gabriel439** [comment]
Note that if the only thing users can do with `Version`s is build them with `v` then it's the same as using `Text` for `VersionRange` with a custom `extract` function

**Comment by ocharles** [comment]
> Note that if the only thing users can do with Versions is build them with v then it's the same as using Text for VersionRange with a custom extract function

While technically true, using `Version` does a much better job and documenting intent, and makes it much harder to do things like concatenate versions together. Yes, you *can* still do it, but you have to work pretty hard to do that. I consider that a feature.

**Comment by ocharles** [comment]
Cheers for the brainstorming on this. I think we've both come out winners with this :smile:

**Comment by Gabriel439** [comment]
Yeah, I'm very happy with how this turned out :)

**Comment by Gabriel439** [comment]
I also realized that you can slightly simplify `VersionRange` by just using the type `{ versionRange : Text }` (i.e. the Dhall analog of a Haskell newtype) since you don't need a recursive type

**Comment by ocharles** [comment]
I'm not quite following that - what would I change?

**Comment by Gabriel439** [comment]
`./Version.dhall` would change from this:

```haskell
∀(Version : Type) → ∀(v : Text → Version) → Version
```

... to this

```haskell
{ versionString : Text }
```

**Comment by ocharles** [comment]
Ah, Version, not VersionRange. That sounds good to me

**Pull request merged**
